version: '2'
volumes:
  settings:
services:
  kiosk:
    restart: always
    build: ./kiosk
    privileged: true
    ports:
      - 5011:5011
    volumes:
      - 'settings:/data'
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
  wifi-connect:
    build: ./wifi-connect
    network_mode: "host"
    labels:
        io.balena.features.dbus: '1'
    cap_add:
        - NET_ADMIN
    environment:
        DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
  fbcp:
    build: ./fbcp
    restart: on-failure
    privileged: true
  browsercontrol:
    build: ./browsercontrol
    restart: always
    privileged: true
    ports:
      - 8080:80
